from lib import *
print("ALUMNOS UTECA")
print (" Matricula  |  Nombre         |   Edad    | calf.1   | calf.2 | calf.3 | calf.4 | calf.5 | Promedio| Graduado | Fecha  | Tesis ")
print ("..................................................................................................................................")
alum1= alumnograduado(601049,"ACOSTA  ZAIRA" , 35)
alum1.setCalif(9)
alum1.setCalif(8)
alum1.setCalif (7)
alum1.setCalif (9)
print (alum1)
print(alum1.Setpromedio)
alum1.set_graduado("si","01/07/2013", "Los neutrinos saben a jugo de Uvas")

alum2 = alumnograduado ( 601048, "Frainé", "Durán", "34")
alum2.setCalif(6)
alum2.setCalif(5)
alum2.setCalif(5)
alum2.setCalif(4)
alum2.setCalif(3)
print(alum2)
print(alum2.Setpromedio)
alum2.set_graduado("no","n/a","n/a")

alum3 = alumnograduado( 100738, "Víctor", "García", "20")
alum3.setCalif(8)
alum3.setCalif(3)
alum3.setCalif(4)
alum3.setCalif(5)
alum3.setCalif(4)
print(alum3)
print(alum3.Setpromedio)
alum3.set_graduado("no","n/a","n/a")


alum4 = alumnograduado( 100744, "Diego", "López", "18")
alum4.setCalif(10)
alum4.setCalif(9)
alum4.setCalif(8)
alum4.setCalif(10)
alum4.setCalif(8)
print(alum4)
print(alum4.Setpromedio)
alum4.set_graduado("Si","01/05/2026","Por que los polleros cortan 2 veces al aire y una al pollo")

alum5 = alumnograduado ( 100692, "Evelyn", "López", "19")
alum5.setCalif(10)
alum5.setCalif(8)
alum5.setCalif(9)
alum5.setCalif(5)
alum5.setCalif(9)
print(alum5)
print(alum5.Setpromedio)
alum5.set_graduado("Si",	"01/05/2027" ,"El hot dog ¿mas cerca del sandwich o del taco?")

alum6 = alumnograduado ( 99999 , "Daniel", "Rojas", "20")
alum6.setCalif(6)
alum6.setCalif(5)
alum6.setCalif(4)
alum6.setCalif(4)
alum6.setCalif(3)
print(alum6)
print(alum6.Setpromedio)
alum6.set_graduado("No","N/A","N/A")

alum7 = alumnograduado (100870, "Mauricio", "Rosas", "20")
alum7.setCalif(10)
alum7.setCalif(6)
alum7.setCalif(10)
alum7.setCalif(9)
alum7.setCalif(8)
print(alum7)
print(alum7.Setpromedio)
alum7.set_graduado("Si"	,"01/08/2026", "La telenovela Mirada de mujer como fenomeno social ")

alum8 = alumnograduado( 100437, "Annibal", "Villegas", "20")
alum8.setCalif(10)
alum8.setCalif(5)
alum8.setCalif(7)
alum8.setCalif(8)
alum8.setCalif(9)
print(alum8)
print(alum8.Setpromedio)
print(alum8.set_graduado)

